### ISSUE TITLE
invalid load key, '\x1f'

### ISSUE THREAD

**Issue by evaninf** [chaojie/ComfyUI_StreamingT2V#14]
After automatically downloading the 5.65G model I only get this error when trying to test:

```
PIPE LOADING DONE
CUSTOM XFORMERS ATTENTION USED.
!!! Exception during processing!!! invalid load key, '\x1f'.
Traceback (most recent call last):
  File "/opt/comfy/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/comfy/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/comfy/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/comfy/custom_nodes/ComfyUI_StreamingT2V/nodes.py", line 91, in run
    stream_cli, stream_model = init_streamingt2v_model(Path(ckpt_file_streaming_t2v).absolute(), Path(result_fol).absolute(),vram_not_enough)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/comfy/custom_nodes/ComfyUI_StreamingT2V/model_init.py", line 109, in init_streamingt2v_model
    model.load_state_dict(torch.load(cli.config["ckpt"].as_posix(),map_location='cpu')["state_dict"])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/.local/lib/python3.11/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/.local/lib/python3.11/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '\x1f'.
```

**Comment by Chen-jia621** [comment]
load laion/CLIP-ViT-H-14-laion2B-s32B-b79K/open_clip_pytorch_model.bin ; not .safetensors
