### ISSUE TITLE
No module named 'diffusers.models.transformer_temporal

### ISSUE THREAD

**Issue by nieli123456** [chaojie/ComfyUI_StreamingT2V#16]
!!! Exception during processing !!! No module named 'diffusers.models.transformer_temporal'
Traceback (most recent call last):
  File "d:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "d:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StreamingT2V\nodes.py", line 399, in run
    from vidxtend import VidXTendPipeline
  File "d:\ComfyUI_windows_portable\ComfyUI/custom_nodes/ComfyUI_StreamingT2V/thirdparty\vidxtend\__init__.py", line 10, in <module>
    sys.modules[f"{__name__}.{dirname}.{model_name}"] = __import__(f"{__name__}.{dirname}.{model_name}", fromlist=[model_name])
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ComfyUI_windows_portable\ComfyUI/custom_nodes/ComfyUI_StreamingT2V/thirdparty\vidxtend\models\__init__.py", line 3, in <module>
    from vidxtend.models.conditioning import CrossAttention, ConditionalModel
  File "d:\ComfyUI_windows_portable\ComfyUI/custom_nodes/ComfyUI_StreamingT2V/thirdparty\vidxtend\models\conditioning.py", line 6, in <module>
    from diffusers.models.transformer_temporal import (
ModuleNotFoundError: No module named 'diffusers.models.transformer_temporal'

**Comment by Chen-jia621** [comment]
from diffusers.models.transformers.transformer_temporal import xxx

**Comment by rodsott** [comment]
I'm having this issue too.. any idea on how to fix this?

StreamingT2VLoaderModelscopeT2V
No module named 'diffusers.models.transformer_temporal'
